Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('VT.urls', namespace="Home")),
    path('', include('users.urls', namespace="users")),
]

templates/Users/add_user.html
{% extends 'VT/base.html' %}
{% load static %}

      {% block page_name %}
             edit
        {% endblock %}
{% block content %}
 <div class="testimonial">
    <h2>Add Product</h2>
    <div class="small-container">
    <div class="row">
        <div class="col-3">
            <form id="LoginForm" method="POST" action="{% url "users:added" %}">
                {% csrf_token %}
                <input type="text" placeholder="Username" name="username" >
                <input type="text" placeholder="First Name" name="first_name">
                <input type="text" placeholder="Last Name" name="last_name">
                <input type="email" placeholder="Email" name="email">
                <input type="radio" id="admin" name="role" value="admin">
                <label for="admin">Admin</label>
                <input type="radio" id="regular" name="role" value="regular">
                <label for="regular">Regular</label>
                <input type="Password" placeholder="Enter password " name="password">
                <button type="submit" class="btn">Add User</button>
            </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

<!----------offer--------------->


<!----------Footer--------------->

<div class="footer">
    <div class="container">
        <div class="row">
            <div class="footer-col1">
               <h3>Download Our App</h3>
                <p>Download App for Android and ios mobile phone.</p>
                <div class="app-logo">
                    <img src="{% static "img/play-store.png" %}">
                    <img src="{% static "img/app-store.png"%}">
                </div>
            </div>
            <div class="footer-col2">
               <img src="{% static "img/logo-white.png" %}" >
                <p>Our Purpose Is To Sustainably Make the Pleasure and Benefits of Sports Accessible to the Many.</p>
            </div>
            <div class="footer-col3">
               <h3>Useful Links</h3>
                <ul>
                    <li>Coupons</li>
                    <li>Blog Post</li>
                    <li>Return Policy</li>
                    <li>Join Affiliate</li>
                </ul>
            </div>
            <div class="footer-col4">
               <h3>Follow Us</h3>
                <ul>
                    <li>Facebook</li>
                    <li>Twitter<li>
                    <li>Instagram</li>
                    <li>YouTube</li>
                </ul>
            </div>
        </div>
        <hr>
    </div>
</div>

<div class="social-panel-container">
	<div class="social-panel">
		<p>Created with <i class="fa fa-heart"></i> by
			<a target="_blank" href="#">VTEssentials</a></p>
		<button class="close-btn"><i class="fa fa-times"></i></button>
		<h4>Get in touch on</h4>
		<ul>
			<li>
					<i class="fa fa-twitter"></i>
			</li>
			<li>
					<i class="fa fa-linkedin"></i>
			</li>
			<li>
					<i class="fa fa-facebook"></i>
			</li>
			<li>
					<i class="fa fa-instagram"></i>
			</li>
		</ul>
	</div>
</div>
<button class="floating-btn">
	Get in Touch
</button>



<!-------------js for toggle menu-------------->
   {% load static %}
<script src="{% static 'js/app.js' %}"></script>
<script>

    var MenuItems = document.getElementById("MenuItems");

    MenuItems.style.maxHeight = "0px";

    function menutoggle()
    {
        if(MenuItems.style.maxHeight == "0px")
            {
                MenuItems.style.maxHeight = "300px";
            }else
            {
                MenuItems.style.maxHeight = "0px"
            }
    }
</script>
<script>
    $(document).ready(function(){
$('div.col-2 button.cartbtn').click(function(){
    varnumber
    $(counter).html(number);
    var counter= document.getElementById('counter');

    var number=parseInt($(counter).text());
    number++;

    $(counter).html(number);
})
})

</script>
</body>
</html>


templates/Users/comment.html
{% extends 'VT/base.html' %}
{% load static %}

      {% block page_name %}
             edit
        {% endblock %}
{% block content %}
 <div class="testimonial">
    <h2>Add Review</h2>
    <div class="small-container">
    <div class="row">
        <div class="col-3">
            <form id="LoginForm" method="POST" action="{% url 'user:comment_added' %}">
                {% csrf_token %}
                <input type="text" id="username" placeholder="{{ user.username }}" name="username" value="{{ request.session.user }}" disabled >
                <label for="title"></label><input type="text" id="title" placeholder="{{ item.price }}" name="title" value="{{ request.session.title }}" disabled>
                <label for="user_id">Enter Your User Id</label><input type="text" id="user_id" name="user_id">
                  <label for="item_id">Enter Product Id</label><input type="text"   name="item_id" >
                <textarea name="comment" id="comment" cols="36" rows="10" placeholder="Review" style="font-family:'Poppins', sans-serif; margin-top: 2rem;"></textarea>
                <button type="submit" class="btn comment">Add Comment</button>
            </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

<!----------offer--------------->


<!----------Footer--------------->

<div class="footer">
    <div class="container">
        <div class="row">
            <div class="footer-col1">
               <h3>Download Our App</h3>
                <p>Download App for Android and ios mobile phone.</p>
                <div class="app-logo">
                    <img src="{% static "img/play-store.png" %}">
                    <img src="{% static "img/app-store.png"%}">
                </div>
            </div>
            <div class="footer-col2">
               <img src="{% static "img/logo-white.png" %}" >
                <p>Our Purpose Is To Sustainably Make the Pleasure and Benefits of Sports Accessible to the Many.</p>
            </div>
            <div class="footer-col3">
               <h3>Useful Links</h3>
                <ul>
                    <li>Coupons</li>
                    <li>Blog Post</li>
                    <li>Return Policy</li>
                    <li>Join Affiliate</li>
                </ul>
            </div>
            <div class="footer-col4">
               <h3>Follow Us</h3>
                <ul>
                    <li>Facebook</li>
                    <li>Twitter<li>
                    <li>Instagram</li>
                    <li>YouTube</li>
                </ul>
            </div>
        </div>
        <hr>
    </div>
</div>

<div class="social-panel-container">
	<div class="social-panel">
		<p>Created with <i class="fa fa-heart"></i> by
			<a target="_blank" href="#">VTEssentials</a></p>
		<button class="close-btn"><i class="fa fa-times"></i></button>
		<h4>Get in touch on</h4>
		<ul>
			<li>
					<i class="fa fa-twitter"></i>
			</li>
			<li>
					<i class="fa fa-linkedin"></i>
			</li>
			<li>
					<i class="fa fa-facebook"></i>
			</li>
			<li>
					<i class="fa fa-instagram"></i>
			</li>
		</ul>
	</div>
</div>
<button class="floating-btn">
	Get in Touch
</button>



<!-------------js for toggle menu-------------->
   {% load static %}
<script src="{% static 'js/app.js' %}"></script>
<script>

    var MenuItems = document.getElementById("MenuItems");

    MenuItems.style.maxHeight = "0px";

    function menutoggle()
    {
        if(MenuItems.style.maxHeight == "0px")
            {
                MenuItems.style.maxHeight = "300px";
            }else
            {
                MenuItems.style.maxHeight = "0px"
            }
    }
</script>
<script>
    $(document).ready(function(){
$('div.col-2 button.cartbtn').click(function(){
    varnumber
    $(counter).html(number);
    var counter= document.getElementById('counter');

    var number=parseInt($(counter).text());
    number++;

    $(counter).html(number);
})
})

</script>
</body>
</html>


templates/Users/comment_preview.html
{% extends 'VT/base.html' %}
{% load static %}

      {% block page_name %}
             edit
        {% endblock %}
{% block content %}
 <div class="testimonial">
    <h2>Add Review</h2>
    <div class="small-container">
    <div class="row">
        <div class="col-3">
            <form id="LoginForm" method="POST" action="{% url 'user:comment_edited' %}">
                {% csrf_token %}
                <label for="username">Commented by Userid</label><input type="text" id="username" placeholder="{{ user.username }}" name="username" value="{{  request.session.user_id }}" disabled >
                <label for="title">Commented for Item id</label><input type="text"  name="item_id" value="{{ request.session.item_id}}" disabled>
                <input type="hidden" id=""  name="comment_id" value="{{ request.session.comment_id }}">
                <textarea name="review" id="comment" cols="36" rows="10" placeholder="Review"   style="font-family:'Poppins', sans-serif; margin-top: 2rem;"></textarea>
                <button type="submit" class="btn comment" d>Edit Comment</button>
            </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

<!----------offer--------------->


<!----------Footer--------------->

<div class="footer">
    <div class="container">
        <div class="row">
            <div class="footer-col1">
               <h3>Download Our App</h3>
                <p>Download App for Android and ios mobile phone.</p>
                <div class="app-logo">
                    <img src="{% static "img/play-store.png" %}">
                    <img src="{% static "img/app-store.png"%}">
                </div>
            </div>
            <div class="footer-col2">
               <img src="{% static "img/logo-white.png" %}" >
                <p>Our Purpose Is To Sustainably Make the Pleasure and Benefits of Sports Accessible to the Many.</p>
            </div>
            <div class="footer-col3">
               <h3>Useful Links</h3>
                <ul>
                    <li>Coupons</li>
                    <li>Blog Post</li>
                    <li>Return Policy</li>
                    <li>Join Affiliate</li>
                </ul>
            </div>
            <div class="footer-col4">
               <h3>Follow Us</h3>
                <ul>
                    <li>Facebook</li>
                    <li>Twitter<li>
                    <li>Instagram</li>
                    <li>YouTube</li>
                </ul>
            </div>
        </div>
        <hr>
    </div>
</div>

<div class="social-panel-container">
	<div class="social-panel">
		<p>Created with <i class="fa fa-heart"></i> by
			<a target="_blank" href="#">VTEssentials</a></p>
		<button class="close-btn"><i class="fa fa-times"></i></button>
		<h4>Get in touch on</h4>
		<ul>
			<li>
					<i class="fa fa-twitter"></i>
			</li>
			<li>
					<i class="fa fa-linkedin"></i>
			</li>
			<li>
					<i class="fa fa-facebook"></i>
			</li>
			<li>
					<i class="fa fa-instagram"></i>
			</li>
		</ul>
	</div>
</div>
<button class="floating-btn">
	Get in Touch
</button>



<!-------------js for toggle menu-------------->
   {% load static %}
<script src="{% static 'js/app.js' %}"></script>
<script>

    var MenuItems = document.getElementById("MenuItems");

    MenuItems.style.maxHeight = "0px";

    function menutoggle()
    {
        if(MenuItems.style.maxHeight == "0px")
            {
                MenuItems.style.maxHeight = "300px";
            }else
            {
                MenuItems.style.maxHeight = "0px"
            }
    }
</script>
<script>
    $(document).ready(function(){
$('div.col-2 button.cartbtn').click(function(){
    varnumber
    $(counter).html(number);
    var counter= document.getElementById('counter');

    var number=parseInt($(counter).text());
    number++;

    $(counter).html(number);
})
})

</script>
</body>
</html>


templates/Users/edit.html
{% extends 'VT/base.html' %}
{% load static %}
      {% block page_name %}
             edit
        {% endblock %}
{% block content %}
 <div class="testimonial">
    <h2>Add Product</h2>
    <div class="small-container">
    <div class="row">
        <div class="col-3">
            <form id="LoginForm" method="POST" action="{% url "users:edit_preview" %}">
                {% csrf_token %}
                <input type="text" placeholder="*Username :- {{  request.session.username }}" name="username" disabled>
                <input type="text" placeholder="{{  request.session.user_id }}" name="user_id" disabled>
                <input type="text" placeholder="First Name:-{{  request.session.first_name }}" name="first_name">
                <input type="text" placeholder="Last Name:-{{  request.session.last_name }}" name="last_name">
                <input type="email" placeholder="Email:-{{  request.session.email }}" name="email">
                <input type="Password" placeholder="Enter New password " name="new_password">
                <input type="Password" placeholder="Enter old password to confirm change " name="password">
                <button type="submit" class="btn">Confirm Changes</button>
                <p>* cannot be modified</p>
            </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

<!----------offer--------------->


<!----------Footer--------------->

<div class="footer">
    <div class="container">
        <div class="row">
            <div class="footer-col1">
               <h3>Download Our App</h3>
                <p>Download App for Android and ios mobile phone.</p>
                <div class="app-logo">
                    <img src="{% static "img/play-store.png" %}">
                    <img src="{% static "img/app-store.png"%}">
                </div>
            </div>
            <div class="footer-col2">
               <img src="{% static "img/logo-white.png" %}" >
                <p>Our Purpose Is To Sustainably Make the Pleasure and Benefits of Sports Accessible to the Many.</p>
            </div>
            <div class="footer-col3">
               <h3>Useful Links</h3>
                <ul>
                    <li>Coupons</li>
                    <li>Blog Post</li>
                    <li>Return Policy</li>
                    <li>Join Affiliate</li>
                </ul>
            </div>
            <div class="footer-col4">
               <h3>Follow Us</h3>
                <ul>
                    <li>Facebook</li>
                    <li>Twitter<li>
                    <li>Instagram</li>
                    <li>YouTube</li>
                </ul>
            </div>
        </div>
        <hr>
    </div>
</div>

<div class="social-panel-container">
	<div class="social-panel">
		<p>Created with <i class="fa fa-heart"></i> by
			<a target="_blank" href="#">VTEssentials</a></p>
		<button class="close-btn"><i class="fa fa-times"></i></button>
		<h4>Get in touch on</h4>
		<ul>
			<li>
					<i class="fa fa-twitter"></i>
			</li>
			<li>
					<i class="fa fa-linkedin"></i>
			</li>
			<li>
					<i class="fa fa-facebook"></i>
			</li>
			<li>
					<i class="fa fa-instagram"></i>
			</li>
		</ul>
	</div>
</div>
<button class="floating-btn">
	Get in Touch
</button>



<!-------------js for toggle menu-------------->
   {% load static %}
<script src="{% static 'js/app.js' %}"></script>
<script>

    var MenuItems = document.getElementById("MenuItems");

    MenuItems.style.maxHeight = "0px";

    function menutoggle()
    {
        if(MenuItems.style.maxHeight == "0px")
            {
                MenuItems.style.maxHeight = "300px";
            }else
            {
                MenuItems.style.maxHeight = "0px"
            }
    }
</script>
</body>
</html>


templates/Users/edit_user.html
{% extends 'VT/base.html' %}
{% load static %}

      {% block page_name %}
             edit
        {% endblock %}
{% block content %}
 <div class="testimonial">
    <h2>Add Product</h2>
    <div class="small-container">
    <div class="row">
        <div class="col-3">

            <form id="LoginForm" method="POST" action="{% url "users:admin_review" %}">
                {% csrf_token %}
                <input type="hidden" placeholder="" name="user_id">
                 <input type="text" placeholder="*Username :- " name="username"  >
                <input type="text" placeholder="First Name:-" name="first_name">
                <input type="text" placeholder="Last Name:" name="last_name">
                <input type="email" placeholder="Email" name="email">
                <input type="Password" placeholder="Enter New password " name="new_password">
                <input type="Password" placeholder="Enter old password to confirm change " name="password">
                <button type="submit" class="btn">Confirm Changes</button>
                <p>* cannot be modified</p>
            </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

<!----------offer--------------->


<!----------Footer--------------->

<div class="footer">
    <div class="container">
        <div class="row">
            <div class="footer-col1">
               <h3>Download Our App</h3>
                <p>Download App for Android and ios mobile phone.</p>
                <div class="app-logo">
                    <img src="{% static "img/play-store.png" %}">
                    <img src="{% static "img/app-store.png"%}">
                </div>
            </div>
            <div class="footer-col2">
               <img src="{% static "img/logo-white.png" %}" >
                <p>Our Purpose Is To Sustainably Make the Pleasure and Benefits of Sports Accessible to the Many.</p>
            </div>
            <div class="footer-col3">
               <h3>Useful Links</h3>
                <ul>
                    <li>Coupons</li>
                    <li>Blog Post</li>
                    <li>Return Policy</li>
                    <li>Join Affiliate</li>
                </ul>
            </div>
            <div class="footer-col4">
               <h3>Follow Us</h3>
                <ul>
                    <li>Facebook</li>
                    <li>Twitter<li>
                    <li>Instagram</li>
                    <li>YouTube</li>
                </ul>
            </div>
        </div>
        <hr>
    </div>
</div>

<div class="social-panel-container">
	<div class="social-panel">
		<p>Created with <i class="fa fa-heart"></i> by
			<a target="_blank" href="#">VTEssentials</a></p>
		<button class="close-btn"><i class="fa fa-times"></i></button>
		<h4>Get in touch on</h4>
		<ul>
			<li>
					<i class="fa fa-twitter"></i>
			</li>
			<li>
					<i class="fa fa-linkedin"></i>
			</li>
			<li>
					<i class="fa fa-facebook"></i>
			</li>
			<li>
					<i class="fa fa-instagram"></i>
			</li>
		</ul>
	</div>
</div>
<button class="floating-btn">
	Get in Touch
</button>



<!-------------js for toggle menu-------------->
   {% load static %}
<script src="{% static 'js/app.js' %}"></script>
<script>

    var MenuItems = document.getElementById("MenuItems");

    MenuItems.style.maxHeight = "0px";

    function menutoggle()
    {
        if(MenuItems.style.maxHeight == "0px")
            {
                MenuItems.style.maxHeight = "300px";
            }else
            {
                MenuItems.style.maxHeight = "0px"
            }
    }
</script>
<script>
    $(document).ready(function(){
$('div.col-2 button.cartbtn').click(function(){
    varnumber
    $(counter).html(number);
    var counter= document.getElementById('counter');

    var number=parseInt($(counter).text());
    number++;

    $(counter).html(number);
})
})

</script>
</body>
</html>


templates/Users/profile.html
{% extends 'VT/base.html' %}
{% load static %}
{% load humanize %}
{% block page_name %}
    Profile
{% endblock %}
 {% block login_form %}
         <form id="log" action="{% url 'VTessential:login' %}" method="POST" style="width: 10rem; margin-left: 2rem;margin-right: 2rem;height: 10rem">
                   {% csrf_token %}
                   <input style="height: 1.5rem" type="text" placeholder="Username" name="username">
                   <input style="height: 1.5rem" type="password" placeholder="Password" name="password">
                   <input style="height: 2rem" type="submit" class="btn" name="Login">
                   <a href="">Forgot password</a>
               </form>
  {% endblock %}
{% block detail_page %}
     <div class="col-2">
        {% load static %}
             <img src="{% static "img/user-1.png"%}" width="50%" id="ProductImg">
             <div class="small-img-row">
         </div>
         </div>
        <div class="col-2">
        <form action="{% url "user:edit" %}" method="POST">{% csrf_token %}
            <h4>Profile Information</h4>
            <input type="hidden" name="user_id" value="{{ user.id }}">
            <h3> UserId:- {{ user.id }}</h3>
            <input type="hidden" name="first_name" value="{{ user.first_name }}">
            <h3> First Name:- {{ user.first_name }}</h3>
            <input type="hidden" name="last_name" value="{{ user.last_name }}">
            <h3> Last Name:- {{ user.last_name }}</h3>
            <input type="hidden" name="username" value="{{ user.username }}">
            <h3> Username:- {{ user.username }}</h3>
            <input type="hidden" name="email" value="{{ user.email }}">
            <h3> Email:- {{ user.email }}</h3>
            <input type="hidden" name="password" value="{{ user.password }}">
            <input type="hidden" name="role" value="{{ user.details.role }}">
            <h3> User Role:- {{ user.details.role }}</h3>
            <button type="submit" class="btn">Edit</button>
        </form>
        </div>
    </div>
</div>
{% endblock %}
{% block content %}
     <div class="testimonial">
    <div class="small-container">
              <h2 class="title">Recent Activity</h2>
    <div class="row">
        {% for action in action %}
        <div class="col-3">
            <p> <a style="color: #ff523b" href="{% url 'user:profile' action.user.username %}">{{ action.user }}</a> {{ action.verb }} to <a style="color: #ff523b" href="{% url 'VTessential:item_detail' action.target.id %}"> {{ action.target.title  }}</a>{{ action.created|naturaltime  }}</p>
        </div>
        {% endfor %}
    </div>
    </div>
</div>
{% endblock %}


    {% block item_list %}
     <div class="row">
           {% for item in items %}
               <div class="col-4">
               {% if item.type == "T-shirt" or item.type == "Tshirt" or item.type == "t-shirt" %}
                    <a href="{% url "VTessential:item_detail" item.id %}"><img src="{% static "img/product-1.jpg" %}"></a>
                {% elif item.type == "shoes" or item.type == "Shoes" %}
                    <a href="{% url "VTessential:item_detail" item.id %}"><img src="{% static "img/product-2.jpg" %}"></a>
                {% endif %}
                   <h4><a href="{% url "VTessential:item_detail" item.id %}">{{ item.title }}</a></h4>
               <h4><a href="{% url "VTessential:item_detail" item.id %}">Product Id - <b>{{ item.id }}</b></a></h4>
                   <div class="rating">
               {% if item.rating == 5 %}
                   <i class="fa fa-star"></i>
                   <i class="fa fa-star"></i>
                   <i class="fa fa-star"></i>
                   <i class="fa fa-star"></i>
                   <i class="fa fa-star"></i>
               {% elif item.rating == 4 %}
                   <i class="fa fa-star"></i>
                   <i class="fa fa-star"></i>
                   <i class="fa fa-star"></i>
                   <i class="fa fa-star"></i>
                   <i class="fa fa-star-o"></i>
               {% elif item.rating == 4.5 %}
                   <i class="fa fa-star"></i>
                   <i class="fa fa-star"></i>
                   <i class="fa fa-star"></i>
                   <i class="fa fa-star"></i>
                   <i class="fa fa-star-half-o"></i>
               {% elif item.rating == 0 %}
                   <span>No ratings</span>
               {% endif %}
                   </div>
                   <p>${{ item.price }}</p>
                   <form action="{% url 'user:comment' %} " method="post">
                       {% csrf_token %}
               <input type="hidden" value="{{ item.title }}"  name="title">
                       <input type="hidden" value="{{ item.id }}">
                       <input type="hidden" value="{{ user.id }}">
               <input type="hidden" value="{{ user.username }}" name="username">
               <button class="btn" >Review</button>
               </form>
               </div>
              {% endfor %}
           </div>
{% endblock %}
{#{% block content %}#}
{#     <div class="testimonial">#}
{#    <h2>Reviews</h2>#}
{#    <div class="small-container">#}
{#    <div class="row">#}
{#          {% for comment in comment %}#}
{#        <div class="col-3">#}
{#                 <i class="fa fa-quote-left"></i>#}
{#                   <p>{{ comment.description }}</p>#}
{#                   <div class="rating">#}
{#                        <i class="fa fa-star"></i>#}
{#                        <i class="fa fa-star"></i>#}
{#                        <i class="fa fa-star"></i>#}
{#                        <i class="fa fa-star"></i>#}
{#                        <i class="fa fa-star-o"></i>#}
{#                    </div>#}
{#        <p>{{ comment.time|naturaltime  }}</p>#}
{#            {% for user in user %}#}
{#                    <a href="{% url 'user:profile' comment.user.username %}"><h3>{{ comment.user.username }}</h3></a>#}
{#                {% endfor %}#}
{#        </div>#}
{#   {% endfor %}#}
{#    </div>#}
{#    </div>#}
{#</div>#}
{#{% endblock %}#}



templates/Users/register.html
{% extends 'VT/base.html' %}
{% block page_name %}
    Register
{% endblock %}
  {% block login_form %}

  {% endblock %}

{% block item_list %}
     {% load static %}
    <div class="testimonial">
    <h2>Register</h2>
    <div class="small-container">
    <div class="row">
        <div class="col-3">
            <form id="LoginForm" method="POST" action="{% url "user:register" %}">
                {% csrf_token %}
                <input type="text" placeholder="Username" name="username">
                <input type="text" placeholder="First Name" name="first_name">
                <input type="text" placeholder="Last Name" name="last_name">
                <input type="email" placeholder="Email" name="email">
                <input type="password" placeholder="password" name="password">
                <button type="submit" class="btn">Submit</button>
                <input type="hidden" name="role" value="regular">
                <p>* cannot be modified</p>
            </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}


templates/Users/user_list.html
{% extends 'VT/base.html' %}
{% load static %}

{% block page_name %}
    Profile
{% endblock %}
 {% block login_form %}
         <form id="log" action="{% url 'VTessential:login' %}" method="POST" style="width: 10rem; margin-left: 2rem;margin-right: 2rem;height: 10rem">
                   {% csrf_token %}
                   <input style="height: 1.5rem" type="text" placeholder="Username" name="username">
                   <input style="height: 1.5rem" type="password" placeholder="Password" name="password">
                   <input style="height: 2rem" type="submit" class="btn" name="Login">
                   <a href="">Forgot password</a>
               </form>
  {% endblock %}
{% block detail_page %}
    {% for user in user %}
     <div class="col-2">
        {% load static %}
             <img src="{% static "img/user-1.png"%}" width="50%" id="ProductImg">
             <div class="small-img-row">
         </div>
         </div>
        <div class="col-2">
        <form action="{% url "user:edit_user" %}" method="POST">
            {% csrf_token %}
            <a href="{% url 'user:profile' user.username %}">View</a>
            <h4>Profile Information</h4>
            <input type="hidden" name="user_id" value="{{ user.id }}">
            <h3> User-id:- {{ user.id }}</h3>
            <h3> First Name:- {{ user.first_name }}</h3>
            <h3> Last Name:- {{ user.last_name }}</h3>
            <h3> Username:- {{ user.username }}</h3>
            <h3> Email:- {{ user.email }}</h3>
            <h3> User Role:- {{ user.details.role }}</h3>
            <button type="submit" class="btn">Edit</button>
        </form>
        </div>
         {% endfor %}
    </div>

</div>

{% endblock %}


templates/VT/pages/warning.html
{% extends 'VT/base.html' %}
{% block page_name %}
    Home
{% endblock %}
  {% block content %}
      <form method="post" action="{% url "VTessential:delete" %}" >
      {% csrf_token %}
      <input type="text" placeholder="Enter product name you want to delete" name="product_name">
        <button class="btn" type="submit">Please Confirm</button>
      </form>
  {% endblock %}